# the compiler: gcc for C program, define as g++ for C++
CC = g++
# compiler flags: 
CFLAGS  = -std=c++14 -Wall -Wextra -Wno-deprecated -Werror -pedantic -pedantic-errors

all:
	g++ nasteroids-par.cpp -o nasteroids-par -fopenmp
